### ISSUE TITLE
plone.formwidget.datetime registrations break plone.schemaeditor Date field edit form

### ISSUE THREAD

**Issue by seanupton** [plone/plone.formwidget.datetime#8]
https://github.com/plone/plone.schemaeditor/blob/master/plone/schemaeditor/fields.py#L20 depends on interface resolution order to determine which schema to use for IDate (Date field).  When plone.formwidget.datetime is not installed, the result will be plone.schemaeditor.schema.IDate -- however, when plone.formwidget.datetime is installed, this lookup breaks.  Compatibility needs to be fixed on one or the other of these packages.  If it is determined that this needs to be in plone.schemaeditor, I will close this issue here and file a trac ticket on dev.plone.org.

**Comment by jensens** [comment]
outdated
